-- Database: GLOBALPLA Metadata version: 2 Exported: Dec 9, 2020
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_COVID_ClockIns" USING 'GCG_COVID_ClockIns.mkd' PAGESIZE=4096 (
 "ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_ID" UNIQUE USING 0,
 "EMPLOYEE_ID" CHAR(50),
 "EMPLOYEE" CHAR(50),
 "STATEMENT" CHAR(500),
 "FLAG" BIT NOT NULL,
 "DATE" DATE,
 "TIME" CHAR(50),
 "USER" CHAR(50),
 "RESOLUTION" LONGVARCHAR );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
