-- Database: GLOBALPLA Metadata version: 2 Exported: Dec 9, 2020
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_COVID_Statements" USING 'GCG_COVID_Statements.mkd' PAGESIZE=4096 (
 "ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_ID" UNIQUE USING 0,
 "STATEMENT_NAME" CHAR(100) NOT NULL,
 "STATEMENT" CHAR(500) NOT NULL,
 "ACTIVE" BIT NOT NULL,
 "DATE_CREATED" CHAR(8) NOT NULL,
 "DATE_MODIFIED" CHAR(8) NOT NULL,
 "USER_CREATED" CHAR(8) NOT NULL,
 "USER_MODIFIED" CHAR(8) NOT NULL );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
